dataset_paths:
  - ${oc.env:DATASET_PATH_1,/kaggle/input/large-captcha-dataset/Large_Captcha_Dataset}
  - ${oc.env:DATASET_PATH_2,/kaggle/input/captcha-dataset}
  - ${oc.env:DATASET_PATH_3,/kaggle/input/comprasnet-captchas/comprasnet_imagensacerto}
  - ${oc.env:DATASET_PATH_4,/kaggle/input/captcha-images}
  - ${oc.env:DATASET_PATH_5,/kaggle/input/captcha-version-2-images}

ban_data:
  - /kaggle/input/large-captcha-dataset/Large_Captcha_Dataset/4q2wA.png

image_size: 256
max_length: 10
batch_size: 32
train_test_split: 0.9
num_workers: 4

special_chars: ["<pad>"]
numerals: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
uppercase: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
lowercase: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

augmentation:
  enabled: true
  transforms:
    - type: RandomRotation
      degrees: 5
    - type: RandomBrightnessContrast
      brightness_limit: 0.1
      contrast_limit: 0.1
    - type: GaussNoise
      var_limit: 10.0